// Generated by Bisonc++ V4.09.02 on Fri, 29 Jan 2016 23:01:03 +0530

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {276, 1}, // 1: translation_unit ->  function_definition
     {276, 2}, // 2: translation_unit ->  translation_unit function_definition
     {277, 3}, // 3: function_definition ->  type_specifier fun_declarator compound_statement
     {278, 1}, // 4: type_specifier (VOID) ->  VOID
     {278, 1}, // 5: type_specifier (INT) ->  INT
     {278, 1}, // 6: type_specifier (FLOAT) ->  FLOAT
     {278, 1}, // 7: type_specifier (STRING_LITERAL) ->  STRING_LITERAL
     {279, 4}, // 8: fun_declarator (IDENTIFIER) ->  IDENTIFIER '(' parameter_list ')'
     {279, 3}, // 9: fun_declarator (IDENTIFIER) ->  IDENTIFIER '(' ')'
     {281, 1}, // 10: parameter_list ->  parameter_declaration
     {281, 3}, // 11: parameter_list (',') ->  parameter_list ',' parameter_declaration
     {282, 2}, // 12: parameter_declaration ->  type_specifier declarator
     {283, 1}, // 13: declarator (IDENTIFIER) ->  IDENTIFIER
     {283, 4}, // 14: declarator ('[') ->  declarator '[' constant_expression ']'
     {284, 1}, // 15: constant_expression (INT_CONSTANT) ->  INT_CONSTANT
     {284, 1}, // 16: constant_expression (FLOAT_CONSTANT) ->  FLOAT_CONSTANT
     {280, 2}, // 17: compound_statement ('{') ->  '{' '}'
     {280, 3}, // 18: compound_statement ('{') ->  '{' statement_list '}'
     {280, 4}, // 19: compound_statement ('{') ->  '{' declaration_list statement_list '}'
     {285, 1}, // 20: statement_list ->  statement
     {285, 2}, // 21: statement_list ->  statement_list statement
     {287, 3}, // 22: statement ('{') ->  '{' statement_list '}'
     {287, 1}, // 23: statement ->  selection_statement
     {287, 1}, // 24: statement ->  iteration_statement
     {287, 1}, // 25: statement ->  assignment_statement
     {287, 3}, // 26: statement (RETURN) ->  RETURN expression ';'
     {290, 1}, // 27: assignment_statement (';') ->  ';'
     {290, 4}, // 28: assignment_statement ('=') ->  l_expression '=' expression ';'
     {291, 1}, // 29: expression ->  logical_and_expression
     {291, 3}, // 30: expression (OR_OP) ->  expression OR_OP logical_and_expression
     {293, 1}, // 31: logical_and_expression ->  equality_expression
     {293, 3}, // 32: logical_and_expression (AND_OP) ->  logical_and_expression AND_OP equality_expression
     {294, 1}, // 33: equality_expression ->  relational_expression
     {294, 3}, // 34: equality_expression (EQ_OP) ->  equality_expression EQ_OP relational_expression
     {294, 3}, // 35: equality_expression (NE_OP) ->  equality_expression NE_OP relational_expression
     {295, 1}, // 36: relational_expression ->  additive_expression
     {295, 3}, // 37: relational_expression ('<') ->  relational_expression '<' additive_expression
     {295, 3}, // 38: relational_expression ('>') ->  relational_expression '>' additive_expression
     {295, 3}, // 39: relational_expression (LE_OP) ->  relational_expression LE_OP additive_expression
     {295, 3}, // 40: relational_expression (GE_OP) ->  relational_expression GE_OP additive_expression
     {296, 1}, // 41: additive_expression ->  multiplicative_expression
     {296, 3}, // 42: additive_expression ('+') ->  additive_expression '+' multiplicative_expression
     {296, 3}, // 43: additive_expression ('-') ->  additive_expression '-' multiplicative_expression
     {297, 1}, // 44: multiplicative_expression ->  unary_expression
     {297, 3}, // 45: multiplicative_expression ('*') ->  multiplicative_expression '*' unary_expression
     {297, 3}, // 46: multiplicative_expression ('/') ->  multiplicative_expression '/' unary_expression
     {298, 1}, // 47: unary_expression ->  postfix_expression
     {298, 2}, // 48: unary_expression ->  unary_operator postfix_expression
     {299, 1}, // 49: postfix_expression ->  primary_expression
     {299, 3}, // 50: postfix_expression (IDENTIFIER) ->  IDENTIFIER '(' ')'
     {299, 4}, // 51: postfix_expression (IDENTIFIER) ->  IDENTIFIER '(' expression_list ')'
     {299, 2}, // 52: postfix_expression (INC_OP) ->  l_expression INC_OP
     {301, 1}, // 53: primary_expression ->  l_expression
     {301, 3}, // 54: primary_expression ('=') ->  l_expression '=' expression
     {301, 1}, // 55: primary_expression (INT_CONSTANT) ->  INT_CONSTANT
     {301, 1}, // 56: primary_expression (FLOAT_CONSTANT) ->  FLOAT_CONSTANT
     {301, 1}, // 57: primary_expression (STRING_LITERAL) ->  STRING_LITERAL
     {301, 3}, // 58: primary_expression ('(') ->  '(' expression ')'
     {292, 1}, // 59: l_expression (IDENTIFIER) ->  IDENTIFIER
     {292, 4}, // 60: l_expression ('[') ->  l_expression '[' expression ']'
     {302, 1}, // 61: expression_list ->  expression
     {302, 3}, // 62: expression_list (',') ->  expression_list ',' expression
     {300, 1}, // 63: unary_operator ('-') ->  '-'
     {300, 1}, // 64: unary_operator ('!') ->  '!'
     {288, 7}, // 65: selection_statement (IF) ->  IF '(' expression ')' statement ELSE statement
     {289, 5}, // 66: iteration_statement (WHILE) ->  WHILE '(' expression ')' statement
     {289, 9}, // 67: iteration_statement (FOR) ->  FOR '(' expression ';' expression ';' expression ')' statement
     {286, 1}, // 68: declaration_list ->  declaration
     {286, 2}, // 69: declaration_list ->  declaration_list declaration
     {303, 3}, // 70: declaration (';') ->  type_specifier declarator_list ';'
     {304, 1}, // 71: declarator_list ->  declarator
     {304, 3}, // 72: declarator_list (',') ->  declarator_list ',' declarator
     {305, 1}, // 73: translation_unit_$ ->  translation_unit
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 8} },                       
    { {       276}, { 1} }, // translation_unit   
    { {       277}, { 2} }, // function_definition
    { {       278}, { 3} }, // type_specifier     
    { {       257}, { 4} }, // VOID               
    { {       258}, { 5} }, // INT                
    { {       259}, { 6} }, // FLOAT              
    { {       268}, { 7} }, // STRING_LITERAL     
    { {         0}, { 0} },                       
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            8} },                       
    { {       277}, {            8} }, // function_definition
    { {       278}, {            3} }, // type_specifier     
    { {       257}, {            4} }, // VOID               
    { {       258}, {            5} }, // INT                
    { {       259}, {            6} }, // FLOAT              
    { {       268}, {            7} }, // STRING_LITERAL     
    { {     _EOF_}, { PARSE_ACCEPT} },                       
    { {         0}, {            0} },                       
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       279}, {  9} }, // fun_declarator
    { {       267}, { 10} }, // IDENTIFIER    
    { {         0}, {  0} },                  
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_7[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  3} },                      
    { {       280}, { 11} }, // compound_statement
    { {       123}, { 12} }, // '{'               
    { {         0}, {  0} },                      
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 13} }, // '('
    { {         0}, {  0} },       
};

SR__ s_11[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, { 22} },                        
    { {       125}, { 14} }, // '}'                 
    { {       285}, { 15} }, // statement_list      
    { {       286}, { 16} }, // declaration_list    
    { {       287}, { 17} }, // statement           
    { {       303}, { 18} }, // declaration         
    { {       123}, { 19} }, // '{'                 
    { {       288}, { 20} }, // selection_statement 
    { {       289}, { 21} }, // iteration_statement 
    { {       290}, { 22} }, // assignment_statement
    { {       262}, { 23} }, // RETURN              
    { {       278}, { 24} }, // type_specifier      
    { {       263}, { 25} }, // IF                  
    { {       265}, { 26} }, // WHILE               
    { {       266}, { 27} }, // FOR                 
    { {        59}, { 28} }, // ';'                 
    { {       292}, { 29} }, // l_expression        
    { {       257}, {  4} }, // VOID                
    { {       258}, {  5} }, // INT                 
    { {       259}, {  6} }, // FLOAT               
    { {       268}, {  7} }, // STRING_LITERAL      
    { {       267}, { 30} }, // IDENTIFIER          
    { {         0}, {  0} },                        
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  9} },                         
    { {       281}, { 31} }, // parameter_list       
    { {        41}, { 32} }, // ')'                  
    { {       282}, { 33} }, // parameter_declaration
    { {       278}, { 34} }, // type_specifier       
    { {       257}, {  4} }, // VOID                 
    { {       258}, {  5} }, // INT                  
    { {       259}, {  6} }, // FLOAT                
    { {       268}, {  7} }, // STRING_LITERAL       
    { {         0}, {  0} },                         
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, { 14} },                        
    { {       125}, { 35} }, // '}'                 
    { {       287}, { 36} }, // statement           
    { {       123}, { 19} }, // '{'                 
    { {       288}, { 20} }, // selection_statement 
    { {       289}, { 21} }, // iteration_statement 
    { {       290}, { 22} }, // assignment_statement
    { {       262}, { 23} }, // RETURN              
    { {       263}, { 25} }, // IF                  
    { {       265}, { 26} }, // WHILE               
    { {       266}, { 27} }, // FOR                 
    { {        59}, { 28} }, // ';'                 
    { {       292}, { 29} }, // l_expression        
    { {       267}, { 30} }, // IDENTIFIER          
    { {         0}, {  0} },                        
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, { 20} },                        
    { {       285}, { 37} }, // statement_list      
    { {       303}, { 38} }, // declaration         
    { {       287}, { 17} }, // statement           
    { {       278}, { 24} }, // type_specifier      
    { {       123}, { 19} }, // '{'                 
    { {       288}, { 20} }, // selection_statement 
    { {       289}, { 21} }, // iteration_statement 
    { {       290}, { 22} }, // assignment_statement
    { {       262}, { 23} }, // RETURN              
    { {       257}, {  4} }, // VOID                
    { {       258}, {  5} }, // INT                 
    { {       259}, {  6} }, // FLOAT               
    { {       268}, {  7} }, // STRING_LITERAL      
    { {       263}, { 25} }, // IF                  
    { {       265}, { 26} }, // WHILE               
    { {       266}, { 27} }, // FOR                 
    { {        59}, { 28} }, // ';'                 
    { {       292}, { 29} }, // l_expression        
    { {       267}, { 30} }, // IDENTIFIER          
    { {         0}, {  0} },                        
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, { 14} },                        
    { {       285}, { 39} }, // statement_list      
    { {       287}, { 17} }, // statement           
    { {       123}, { 19} }, // '{'                 
    { {       288}, { 20} }, // selection_statement 
    { {       289}, { 21} }, // iteration_statement 
    { {       290}, { 22} }, // assignment_statement
    { {       262}, { 23} }, // RETURN              
    { {       263}, { 25} }, // IF                  
    { {       265}, { 26} }, // WHILE               
    { {       266}, { 27} }, // FOR                 
    { {        59}, { 28} }, // ';'                 
    { {       292}, { 29} }, // l_expression        
    { {       267}, { 30} }, // IDENTIFIER          
    { {         0}, {  0} },                        
};

SR__ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       291}, { 40} }, // expression               
    { {       293}, { 41} }, // logical_and_expression   
    { {       294}, { 42} }, // equality_expression      
    { {       295}, { 43} }, // relational_expression    
    { {       296}, { 44} }, // additive_expression      
    { {       297}, { 45} }, // multiplicative_expression
    { {       298}, { 46} }, // unary_expression         
    { {       299}, { 47} }, // postfix_expression       
    { {       300}, { 48} }, // unary_operator           
    { {       301}, { 49} }, // primary_expression       
    { {       267}, { 50} }, // IDENTIFIER               
    { {       292}, { 51} }, // l_expression             
    { {        45}, { 52} }, // '-'                      
    { {        33}, { 53} }, // '!'                      
    { {       260}, { 54} }, // INT_CONSTANT             
    { {       261}, { 55} }, // FLOAT_CONSTANT           
    { {       268}, { 56} }, // STRING_LITERAL           
    { {        40}, { 57} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  4} },                   
    { {       304}, { 58} }, // declarator_list
    { {       283}, { 59} }, // declarator     
    { {       267}, { 60} }, // IDENTIFIER     
    { {         0}, {  0} },                   
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 61} }, // '('
    { {         0}, {  0} },       
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 62} }, // '('
    { {         0}, {  0} },       
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 63} }, // '('
    { {         0}, {  0} },       
};

SR__ s_28[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        61}, { 64} }, // '='
    { {        91}, { 65} }, // '['
    { {         0}, {  0} },       
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -59} }, 
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 66} }, // ')'
    { {        44}, { 67} }, // ','
    { {         0}, {  0} },       
};

SR__ s_32[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  3} },              
    { {       283}, { 68} }, // declarator
    { {       267}, { 60} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, { 14} },                        
    { {       125}, { 69} }, // '}'                 
    { {       287}, { 36} }, // statement           
    { {       123}, { 19} }, // '{'                 
    { {       288}, { 20} }, // selection_statement 
    { {       289}, { 21} }, // iteration_statement 
    { {       290}, { 22} }, // assignment_statement
    { {       262}, { 23} }, // RETURN              
    { {       263}, { 25} }, // IF                  
    { {       265}, { 26} }, // WHILE               
    { {       266}, { 27} }, // FOR                 
    { {        59}, { 28} }, // ';'                 
    { {       292}, { 29} }, // l_expression        
    { {       267}, { 30} }, // IDENTIFIER          
    { {         0}, {  0} },                        
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, { 14} },                        
    { {       125}, { 70} }, // '}'                 
    { {       287}, { 36} }, // statement           
    { {       123}, { 19} }, // '{'                 
    { {       288}, { 20} }, // selection_statement 
    { {       289}, { 21} }, // iteration_statement 
    { {       290}, { 22} }, // assignment_statement
    { {       262}, { 23} }, // RETURN              
    { {       263}, { 25} }, // IF                  
    { {       265}, { 26} }, // WHILE               
    { {       266}, { 27} }, // FOR                 
    { {        59}, { 28} }, // ';'                 
    { {       292}, { 29} }, // l_expression        
    { {       267}, { 30} }, // IDENTIFIER          
    { {         0}, {  0} },                        
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {        59}, { 71} }, // ';'  
    { {       273}, { 72} }, // OR_OP
    { {         0}, {  0} },         
};

SR__ s_41[] =
{
    { { REQ_DEF}, {   2} },          
    { {     274}, {  73} }, // AND_OP
    { {       0}, { -29} },          
};

SR__ s_42[] =
{
    { { REQ_DEF}, {   3} },         
    { {     271}, {  74} }, // EQ_OP
    { {     272}, {  75} }, // NE_OP
    { {       0}, { -31} },         
};

SR__ s_43[] =
{
    { { REQ_DEF}, {   5} },         
    { {      60}, {  76} }, // '<'  
    { {      62}, {  77} }, // '>'  
    { {     270}, {  78} }, // LE_OP
    { {     269}, {  79} }, // GE_OP
    { {       0}, { -33} },         
};

SR__ s_44[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  80} }, // '+'
    { {      45}, {  81} }, // '-'
    { {       0}, { -36} },       
};

SR__ s_45[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  82} }, // '*'
    { {      47}, {  83} }, // '/'
    { {       0}, { -41} },       
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_47[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  9} },                      
    { {       299}, { 84} }, // postfix_expression
    { {       301}, { 49} }, // primary_expression
    { {       267}, { 50} }, // IDENTIFIER        
    { {       292}, { 51} }, // l_expression      
    { {       260}, { 54} }, // INT_CONSTANT      
    { {       261}, { 55} }, // FLOAT_CONSTANT    
    { {       268}, { 56} }, // STRING_LITERAL    
    { {        40}, { 57} }, // '('               
    { {         0}, {  0} },                      
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_50[] =
{
    { { REQ_DEF}, {   2} },       
    { {      40}, {  85} }, // '('
    { {       0}, { -59} },       
};

SR__ s_51[] =
{
    { { REQ_DEF}, {   4} },          
    { {     275}, {  86} }, // INC_OP
    { {      61}, {  87} }, // '='   
    { {      91}, {  65} }, // '['   
    { {       0}, { -53} },          
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -63} }, 
};

SR__ s_53[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -64} }, 
};

SR__ s_54[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_55[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_56[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       291}, { 88} }, // expression               
    { {       293}, { 41} }, // logical_and_expression   
    { {       294}, { 42} }, // equality_expression      
    { {       295}, { 43} }, // relational_expression    
    { {       296}, { 44} }, // additive_expression      
    { {       297}, { 45} }, // multiplicative_expression
    { {       298}, { 46} }, // unary_expression         
    { {       299}, { 47} }, // postfix_expression       
    { {       300}, { 48} }, // unary_operator           
    { {       301}, { 49} }, // primary_expression       
    { {       267}, { 50} }, // IDENTIFIER               
    { {       292}, { 51} }, // l_expression             
    { {        45}, { 52} }, // '-'                      
    { {        33}, { 53} }, // '!'                      
    { {       260}, { 54} }, // INT_CONSTANT             
    { {       261}, { 55} }, // FLOAT_CONSTANT           
    { {       268}, { 56} }, // STRING_LITERAL           
    { {        40}, { 57} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 89} }, // ';'
    { {        44}, { 90} }, // ','
    { {         0}, {  0} },       
};

SR__ s_59[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, {  91} }, // '['
    { {       0}, { -71} },       
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       291}, { 92} }, // expression               
    { {       293}, { 41} }, // logical_and_expression   
    { {       294}, { 42} }, // equality_expression      
    { {       295}, { 43} }, // relational_expression    
    { {       296}, { 44} }, // additive_expression      
    { {       297}, { 45} }, // multiplicative_expression
    { {       298}, { 46} }, // unary_expression         
    { {       299}, { 47} }, // postfix_expression       
    { {       300}, { 48} }, // unary_operator           
    { {       301}, { 49} }, // primary_expression       
    { {       267}, { 50} }, // IDENTIFIER               
    { {       292}, { 51} }, // l_expression             
    { {        45}, { 52} }, // '-'                      
    { {        33}, { 53} }, // '!'                      
    { {       260}, { 54} }, // INT_CONSTANT             
    { {       261}, { 55} }, // FLOAT_CONSTANT           
    { {       268}, { 56} }, // STRING_LITERAL           
    { {        40}, { 57} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       291}, { 93} }, // expression               
    { {       293}, { 41} }, // logical_and_expression   
    { {       294}, { 42} }, // equality_expression      
    { {       295}, { 43} }, // relational_expression    
    { {       296}, { 44} }, // additive_expression      
    { {       297}, { 45} }, // multiplicative_expression
    { {       298}, { 46} }, // unary_expression         
    { {       299}, { 47} }, // postfix_expression       
    { {       300}, { 48} }, // unary_operator           
    { {       301}, { 49} }, // primary_expression       
    { {       267}, { 50} }, // IDENTIFIER               
    { {       292}, { 51} }, // l_expression             
    { {        45}, { 52} }, // '-'                      
    { {        33}, { 53} }, // '!'                      
    { {       260}, { 54} }, // INT_CONSTANT             
    { {       261}, { 55} }, // FLOAT_CONSTANT           
    { {       268}, { 56} }, // STRING_LITERAL           
    { {        40}, { 57} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       291}, { 94} }, // expression               
    { {       293}, { 41} }, // logical_and_expression   
    { {       294}, { 42} }, // equality_expression      
    { {       295}, { 43} }, // relational_expression    
    { {       296}, { 44} }, // additive_expression      
    { {       297}, { 45} }, // multiplicative_expression
    { {       298}, { 46} }, // unary_expression         
    { {       299}, { 47} }, // postfix_expression       
    { {       300}, { 48} }, // unary_operator           
    { {       301}, { 49} }, // primary_expression       
    { {       267}, { 50} }, // IDENTIFIER               
    { {       292}, { 51} }, // l_expression             
    { {        45}, { 52} }, // '-'                      
    { {        33}, { 53} }, // '!'                      
    { {       260}, { 54} }, // INT_CONSTANT             
    { {       261}, { 55} }, // FLOAT_CONSTANT           
    { {       268}, { 56} }, // STRING_LITERAL           
    { {        40}, { 57} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       291}, { 95} }, // expression               
    { {       293}, { 41} }, // logical_and_expression   
    { {       294}, { 42} }, // equality_expression      
    { {       295}, { 43} }, // relational_expression    
    { {       296}, { 44} }, // additive_expression      
    { {       297}, { 45} }, // multiplicative_expression
    { {       298}, { 46} }, // unary_expression         
    { {       299}, { 47} }, // postfix_expression       
    { {       300}, { 48} }, // unary_operator           
    { {       301}, { 49} }, // primary_expression       
    { {       267}, { 50} }, // IDENTIFIER               
    { {       292}, { 51} }, // l_expression             
    { {        45}, { 52} }, // '-'                      
    { {        33}, { 53} }, // '!'                      
    { {       260}, { 54} }, // INT_CONSTANT             
    { {       261}, { 55} }, // FLOAT_CONSTANT           
    { {       268}, { 56} }, // STRING_LITERAL           
    { {        40}, { 57} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       291}, { 96} }, // expression               
    { {       293}, { 41} }, // logical_and_expression   
    { {       294}, { 42} }, // equality_expression      
    { {       295}, { 43} }, // relational_expression    
    { {       296}, { 44} }, // additive_expression      
    { {       297}, { 45} }, // multiplicative_expression
    { {       298}, { 46} }, // unary_expression         
    { {       299}, { 47} }, // postfix_expression       
    { {       300}, { 48} }, // unary_operator           
    { {       301}, { 49} }, // primary_expression       
    { {       267}, { 50} }, // IDENTIFIER               
    { {       292}, { 51} }, // l_expression             
    { {        45}, { 52} }, // '-'                      
    { {        33}, { 53} }, // '!'                      
    { {       260}, { 54} }, // INT_CONSTANT             
    { {       261}, { 55} }, // FLOAT_CONSTANT           
    { {       268}, { 56} }, // STRING_LITERAL           
    { {        40}, { 57} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_66[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  7} },                         
    { {       282}, { 97} }, // parameter_declaration
    { {       278}, { 34} }, // type_specifier       
    { {       257}, {  4} }, // VOID                 
    { {       258}, {  5} }, // INT                  
    { {       259}, {  6} }, // FLOAT                
    { {       268}, {  7} }, // STRING_LITERAL       
    { {         0}, {  0} },                         
};

SR__ s_68[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, {  91} }, // '['
    { {       0}, { -12} },       
};

SR__ s_69[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_71[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, { 18} },                             
    { {       293}, { 98} }, // logical_and_expression   
    { {       294}, { 42} }, // equality_expression      
    { {       295}, { 43} }, // relational_expression    
    { {       296}, { 44} }, // additive_expression      
    { {       297}, { 45} }, // multiplicative_expression
    { {       298}, { 46} }, // unary_expression         
    { {       299}, { 47} }, // postfix_expression       
    { {       300}, { 48} }, // unary_operator           
    { {       301}, { 49} }, // primary_expression       
    { {       267}, { 50} }, // IDENTIFIER               
    { {       292}, { 51} }, // l_expression             
    { {        45}, { 52} }, // '-'                      
    { {        33}, { 53} }, // '!'                      
    { {       260}, { 54} }, // INT_CONSTANT             
    { {       261}, { 55} }, // FLOAT_CONSTANT           
    { {       268}, { 56} }, // STRING_LITERAL           
    { {        40}, { 57} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, { 17} },                             
    { {       294}, { 99} }, // equality_expression      
    { {       295}, { 43} }, // relational_expression    
    { {       296}, { 44} }, // additive_expression      
    { {       297}, { 45} }, // multiplicative_expression
    { {       298}, { 46} }, // unary_expression         
    { {       299}, { 47} }, // postfix_expression       
    { {       300}, { 48} }, // unary_operator           
    { {       301}, { 49} }, // primary_expression       
    { {       267}, { 50} }, // IDENTIFIER               
    { {       292}, { 51} }, // l_expression             
    { {        45}, { 52} }, // '-'                      
    { {        33}, { 53} }, // '!'                      
    { {       260}, { 54} }, // INT_CONSTANT             
    { {       261}, { 55} }, // FLOAT_CONSTANT           
    { {       268}, { 56} }, // STRING_LITERAL           
    { {        40}, { 57} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, {  16} },                             
    { {       295}, { 100} }, // relational_expression    
    { {       296}, {  44} }, // additive_expression      
    { {       297}, {  45} }, // multiplicative_expression
    { {       298}, {  46} }, // unary_expression         
    { {       299}, {  47} }, // postfix_expression       
    { {       300}, {  48} }, // unary_operator           
    { {       301}, {  49} }, // primary_expression       
    { {       267}, {  50} }, // IDENTIFIER               
    { {       292}, {  51} }, // l_expression             
    { {        45}, {  52} }, // '-'                      
    { {        33}, {  53} }, // '!'                      
    { {       260}, {  54} }, // INT_CONSTANT             
    { {       261}, {  55} }, // FLOAT_CONSTANT           
    { {       268}, {  56} }, // STRING_LITERAL           
    { {        40}, {  57} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {  16} },                             
    { {       295}, { 101} }, // relational_expression    
    { {       296}, {  44} }, // additive_expression      
    { {       297}, {  45} }, // multiplicative_expression
    { {       298}, {  46} }, // unary_expression         
    { {       299}, {  47} }, // postfix_expression       
    { {       300}, {  48} }, // unary_operator           
    { {       301}, {  49} }, // primary_expression       
    { {       267}, {  50} }, // IDENTIFIER               
    { {       292}, {  51} }, // l_expression             
    { {        45}, {  52} }, // '-'                      
    { {        33}, {  53} }, // '!'                      
    { {       260}, {  54} }, // INT_CONSTANT             
    { {       261}, {  55} }, // FLOAT_CONSTANT           
    { {       268}, {  56} }, // STRING_LITERAL           
    { {        40}, {  57} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  15} },                             
    { {       296}, { 102} }, // additive_expression      
    { {       297}, {  45} }, // multiplicative_expression
    { {       298}, {  46} }, // unary_expression         
    { {       299}, {  47} }, // postfix_expression       
    { {       300}, {  48} }, // unary_operator           
    { {       301}, {  49} }, // primary_expression       
    { {       267}, {  50} }, // IDENTIFIER               
    { {       292}, {  51} }, // l_expression             
    { {        45}, {  52} }, // '-'                      
    { {        33}, {  53} }, // '!'                      
    { {       260}, {  54} }, // INT_CONSTANT             
    { {       261}, {  55} }, // FLOAT_CONSTANT           
    { {       268}, {  56} }, // STRING_LITERAL           
    { {        40}, {  57} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  15} },                             
    { {       296}, { 103} }, // additive_expression      
    { {       297}, {  45} }, // multiplicative_expression
    { {       298}, {  46} }, // unary_expression         
    { {       299}, {  47} }, // postfix_expression       
    { {       300}, {  48} }, // unary_operator           
    { {       301}, {  49} }, // primary_expression       
    { {       267}, {  50} }, // IDENTIFIER               
    { {       292}, {  51} }, // l_expression             
    { {        45}, {  52} }, // '-'                      
    { {        33}, {  53} }, // '!'                      
    { {       260}, {  54} }, // INT_CONSTANT             
    { {       261}, {  55} }, // FLOAT_CONSTANT           
    { {       268}, {  56} }, // STRING_LITERAL           
    { {        40}, {  57} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  15} },                             
    { {       296}, { 104} }, // additive_expression      
    { {       297}, {  45} }, // multiplicative_expression
    { {       298}, {  46} }, // unary_expression         
    { {       299}, {  47} }, // postfix_expression       
    { {       300}, {  48} }, // unary_operator           
    { {       301}, {  49} }, // primary_expression       
    { {       267}, {  50} }, // IDENTIFIER               
    { {       292}, {  51} }, // l_expression             
    { {        45}, {  52} }, // '-'                      
    { {        33}, {  53} }, // '!'                      
    { {       260}, {  54} }, // INT_CONSTANT             
    { {       261}, {  55} }, // FLOAT_CONSTANT           
    { {       268}, {  56} }, // STRING_LITERAL           
    { {        40}, {  57} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, {  15} },                             
    { {       296}, { 105} }, // additive_expression      
    { {       297}, {  45} }, // multiplicative_expression
    { {       298}, {  46} }, // unary_expression         
    { {       299}, {  47} }, // postfix_expression       
    { {       300}, {  48} }, // unary_operator           
    { {       301}, {  49} }, // primary_expression       
    { {       267}, {  50} }, // IDENTIFIER               
    { {       292}, {  51} }, // l_expression             
    { {        45}, {  52} }, // '-'                      
    { {        33}, {  53} }, // '!'                      
    { {       260}, {  54} }, // INT_CONSTANT             
    { {       261}, {  55} }, // FLOAT_CONSTANT           
    { {       268}, {  56} }, // STRING_LITERAL           
    { {        40}, {  57} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, {  14} },                             
    { {       297}, { 106} }, // multiplicative_expression
    { {       298}, {  46} }, // unary_expression         
    { {       299}, {  47} }, // postfix_expression       
    { {       300}, {  48} }, // unary_operator           
    { {       301}, {  49} }, // primary_expression       
    { {       267}, {  50} }, // IDENTIFIER               
    { {       292}, {  51} }, // l_expression             
    { {        45}, {  52} }, // '-'                      
    { {        33}, {  53} }, // '!'                      
    { {       260}, {  54} }, // INT_CONSTANT             
    { {       261}, {  55} }, // FLOAT_CONSTANT           
    { {       268}, {  56} }, // STRING_LITERAL           
    { {        40}, {  57} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {  14} },                             
    { {       297}, { 107} }, // multiplicative_expression
    { {       298}, {  46} }, // unary_expression         
    { {       299}, {  47} }, // postfix_expression       
    { {       300}, {  48} }, // unary_operator           
    { {       301}, {  49} }, // primary_expression       
    { {       267}, {  50} }, // IDENTIFIER               
    { {       292}, {  51} }, // l_expression             
    { {        45}, {  52} }, // '-'                      
    { {        33}, {  53} }, // '!'                      
    { {       260}, {  54} }, // INT_CONSTANT             
    { {       261}, {  55} }, // FLOAT_CONSTANT           
    { {       268}, {  56} }, // STRING_LITERAL           
    { {        40}, {  57} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {  13} },                      
    { {       298}, { 108} }, // unary_expression  
    { {       299}, {  47} }, // postfix_expression
    { {       300}, {  48} }, // unary_operator    
    { {       301}, {  49} }, // primary_expression
    { {       267}, {  50} }, // IDENTIFIER        
    { {       292}, {  51} }, // l_expression      
    { {        45}, {  52} }, // '-'               
    { {        33}, {  53} }, // '!'               
    { {       260}, {  54} }, // INT_CONSTANT      
    { {       261}, {  55} }, // FLOAT_CONSTANT    
    { {       268}, {  56} }, // STRING_LITERAL    
    { {        40}, {  57} }, // '('               
    { {         0}, {   0} },                      
};

SR__ s_83[] =
{
    { { REQ_TOKEN}, {  13} },                      
    { {       298}, { 109} }, // unary_expression  
    { {       299}, {  47} }, // postfix_expression
    { {       300}, {  48} }, // unary_operator    
    { {       301}, {  49} }, // primary_expression
    { {       267}, {  50} }, // IDENTIFIER        
    { {       292}, {  51} }, // l_expression      
    { {        45}, {  52} }, // '-'               
    { {        33}, {  53} }, // '!'               
    { {       260}, {  54} }, // INT_CONSTANT      
    { {       261}, {  55} }, // FLOAT_CONSTANT    
    { {       268}, {  56} }, // STRING_LITERAL    
    { {        40}, {  57} }, // '('               
    { {         0}, {   0} },                      
};

SR__ s_84[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {  21} },                             
    { {        41}, { 110} }, // ')'                      
    { {       302}, { 111} }, // expression_list          
    { {       291}, { 112} }, // expression               
    { {       293}, {  41} }, // logical_and_expression   
    { {       294}, {  42} }, // equality_expression      
    { {       295}, {  43} }, // relational_expression    
    { {       296}, {  44} }, // additive_expression      
    { {       297}, {  45} }, // multiplicative_expression
    { {       298}, {  46} }, // unary_expression         
    { {       299}, {  47} }, // postfix_expression       
    { {       300}, {  48} }, // unary_operator           
    { {       301}, {  49} }, // primary_expression       
    { {       267}, {  50} }, // IDENTIFIER               
    { {       292}, {  51} }, // l_expression             
    { {        45}, {  52} }, // '-'                      
    { {        33}, {  53} }, // '!'                      
    { {       260}, {  54} }, // INT_CONSTANT             
    { {       261}, {  55} }, // FLOAT_CONSTANT           
    { {       268}, {  56} }, // STRING_LITERAL           
    { {        40}, {  57} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {  19} },                             
    { {       291}, { 113} }, // expression               
    { {       293}, {  41} }, // logical_and_expression   
    { {       294}, {  42} }, // equality_expression      
    { {       295}, {  43} }, // relational_expression    
    { {       296}, {  44} }, // additive_expression      
    { {       297}, {  45} }, // multiplicative_expression
    { {       298}, {  46} }, // unary_expression         
    { {       299}, {  47} }, // postfix_expression       
    { {       300}, {  48} }, // unary_operator           
    { {       301}, {  49} }, // primary_expression       
    { {       267}, {  50} }, // IDENTIFIER               
    { {       292}, {  51} }, // l_expression             
    { {        45}, {  52} }, // '-'                      
    { {        33}, {  53} }, // '!'                      
    { {       260}, {  54} }, // INT_CONSTANT             
    { {       261}, {  55} }, // FLOAT_CONSTANT           
    { {       268}, {  56} }, // STRING_LITERAL           
    { {        40}, {  57} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        41}, { 114} }, // ')'  
    { {       273}, {  72} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_89[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};

SR__ s_90[] =
{
    { { REQ_TOKEN}, {   3} },              
    { {       283}, { 115} }, // declarator
    { {       267}, {  60} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR__ s_91[] =
{
    { { REQ_TOKEN}, {   4} },                       
    { {       284}, { 116} }, // constant_expression
    { {       260}, { 117} }, // INT_CONSTANT       
    { {       261}, { 118} }, // FLOAT_CONSTANT     
    { {         0}, {   0} },                       
};

SR__ s_92[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        41}, { 119} }, // ')'  
    { {       273}, {  72} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        41}, { 120} }, // ')'  
    { {       273}, {  72} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_94[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        59}, { 121} }, // ';'  
    { {       273}, {  72} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        59}, { 122} }, // ';'  
    { {       273}, {  72} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        93}, { 123} }, // ']'  
    { {       273}, {  72} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_97[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_98[] =
{
    { { REQ_DEF}, {   2} },          
    { {     274}, {  73} }, // AND_OP
    { {       0}, { -30} },          
};

SR__ s_99[] =
{
    { { REQ_DEF}, {   3} },         
    { {     271}, {  74} }, // EQ_OP
    { {     272}, {  75} }, // NE_OP
    { {       0}, { -32} },         
};

SR__ s_100[] =
{
    { { REQ_DEF}, {   5} },         
    { {      60}, {  76} }, // '<'  
    { {      62}, {  77} }, // '>'  
    { {     270}, {  78} }, // LE_OP
    { {     269}, {  79} }, // GE_OP
    { {       0}, { -34} },         
};

SR__ s_101[] =
{
    { { REQ_DEF}, {   5} },         
    { {      60}, {  76} }, // '<'  
    { {      62}, {  77} }, // '>'  
    { {     270}, {  78} }, // LE_OP
    { {     269}, {  79} }, // GE_OP
    { {       0}, { -35} },         
};

SR__ s_102[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  80} }, // '+'
    { {      45}, {  81} }, // '-'
    { {       0}, { -37} },       
};

SR__ s_103[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  80} }, // '+'
    { {      45}, {  81} }, // '-'
    { {       0}, { -38} },       
};

SR__ s_104[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  80} }, // '+'
    { {      45}, {  81} }, // '-'
    { {       0}, { -39} },       
};

SR__ s_105[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  80} }, // '+'
    { {      45}, {  81} }, // '-'
    { {       0}, { -40} },       
};

SR__ s_106[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  82} }, // '*'
    { {      47}, {  83} }, // '/'
    { {       0}, { -42} },       
};

SR__ s_107[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  82} }, // '*'
    { {      47}, {  83} }, // '/'
    { {       0}, { -43} },       
};

SR__ s_108[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_109[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_110[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_111[] =
{
    { { REQ_TOKEN}, {   3} },       
    { {        41}, { 124} }, // ')'
    { {        44}, { 125} }, // ','
    { {         0}, {   0} },       
};

SR__ s_112[] =
{
    { { REQ_DEF}, {   2} },         
    { {     273}, {  72} }, // OR_OP
    { {       0}, { -61} },         
};

SR__ s_113[] =
{
    { { REQ_DEF}, {   2} },         
    { {     273}, {  72} }, // OR_OP
    { {       0}, { -54} },         
};

SR__ s_114[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_115[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, {  91} }, // '['
    { {       0}, { -72} },       
};

SR__ s_116[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        93}, { 126} }, // ']'
    { {         0}, {   0} },       
};

SR__ s_117[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_118[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_119[] =
{
    { { REQ_TOKEN}, {  13} },                        
    { {       287}, { 127} }, // statement           
    { {       123}, {  19} }, // '{'                 
    { {       288}, {  20} }, // selection_statement 
    { {       289}, {  21} }, // iteration_statement 
    { {       290}, {  22} }, // assignment_statement
    { {       262}, {  23} }, // RETURN              
    { {       263}, {  25} }, // IF                  
    { {       265}, {  26} }, // WHILE               
    { {       266}, {  27} }, // FOR                 
    { {        59}, {  28} }, // ';'                 
    { {       292}, {  29} }, // l_expression        
    { {       267}, {  30} }, // IDENTIFIER          
    { {         0}, {   0} },                        
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {  13} },                        
    { {       287}, { 128} }, // statement           
    { {       123}, {  19} }, // '{'                 
    { {       288}, {  20} }, // selection_statement 
    { {       289}, {  21} }, // iteration_statement 
    { {       290}, {  22} }, // assignment_statement
    { {       262}, {  23} }, // RETURN              
    { {       263}, {  25} }, // IF                  
    { {       265}, {  26} }, // WHILE               
    { {       266}, {  27} }, // FOR                 
    { {        59}, {  28} }, // ';'                 
    { {       292}, {  29} }, // l_expression        
    { {       267}, {  30} }, // IDENTIFIER          
    { {         0}, {   0} },                        
};

SR__ s_121[] =
{
    { { REQ_TOKEN}, {  19} },                             
    { {       291}, { 129} }, // expression               
    { {       293}, {  41} }, // logical_and_expression   
    { {       294}, {  42} }, // equality_expression      
    { {       295}, {  43} }, // relational_expression    
    { {       296}, {  44} }, // additive_expression      
    { {       297}, {  45} }, // multiplicative_expression
    { {       298}, {  46} }, // unary_expression         
    { {       299}, {  47} }, // postfix_expression       
    { {       300}, {  48} }, // unary_operator           
    { {       301}, {  49} }, // primary_expression       
    { {       267}, {  50} }, // IDENTIFIER               
    { {       292}, {  51} }, // l_expression             
    { {        45}, {  52} }, // '-'                      
    { {        33}, {  53} }, // '!'                      
    { {       260}, {  54} }, // INT_CONSTANT             
    { {       261}, {  55} }, // FLOAT_CONSTANT           
    { {       268}, {  56} }, // STRING_LITERAL           
    { {        40}, {  57} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_122[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_123[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_124[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_125[] =
{
    { { REQ_TOKEN}, {  19} },                             
    { {       291}, { 130} }, // expression               
    { {       293}, {  41} }, // logical_and_expression   
    { {       294}, {  42} }, // equality_expression      
    { {       295}, {  43} }, // relational_expression    
    { {       296}, {  44} }, // additive_expression      
    { {       297}, {  45} }, // multiplicative_expression
    { {       298}, {  46} }, // unary_expression         
    { {       299}, {  47} }, // postfix_expression       
    { {       300}, {  48} }, // unary_operator           
    { {       301}, {  49} }, // primary_expression       
    { {       267}, {  50} }, // IDENTIFIER               
    { {       292}, {  51} }, // l_expression             
    { {        45}, {  52} }, // '-'                      
    { {        33}, {  53} }, // '!'                      
    { {       260}, {  54} }, // INT_CONSTANT             
    { {       261}, {  55} }, // FLOAT_CONSTANT           
    { {       268}, {  56} }, // STRING_LITERAL           
    { {        40}, {  57} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_126[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_127[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       264}, { 131} }, // ELSE
    { {         0}, {   0} },        
};

SR__ s_128[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR__ s_129[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        59}, { 132} }, // ';'  
    { {       273}, {  72} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_130[] =
{
    { { REQ_DEF}, {   2} },         
    { {     273}, {  72} }, // OR_OP
    { {       0}, { -62} },         
};

SR__ s_131[] =
{
    { { REQ_TOKEN}, {  13} },                        
    { {       287}, { 133} }, // statement           
    { {       123}, {  19} }, // '{'                 
    { {       288}, {  20} }, // selection_statement 
    { {       289}, {  21} }, // iteration_statement 
    { {       290}, {  22} }, // assignment_statement
    { {       262}, {  23} }, // RETURN              
    { {       263}, {  25} }, // IF                  
    { {       265}, {  26} }, // WHILE               
    { {       266}, {  27} }, // FOR                 
    { {        59}, {  28} }, // ';'                 
    { {       292}, {  29} }, // l_expression        
    { {       267}, {  30} }, // IDENTIFIER          
    { {         0}, {   0} },                        
};

SR__ s_132[] =
{
    { { REQ_TOKEN}, {  19} },                             
    { {       291}, { 134} }, // expression               
    { {       293}, {  41} }, // logical_and_expression   
    { {       294}, {  42} }, // equality_expression      
    { {       295}, {  43} }, // relational_expression    
    { {       296}, {  44} }, // additive_expression      
    { {       297}, {  45} }, // multiplicative_expression
    { {       298}, {  46} }, // unary_expression         
    { {       299}, {  47} }, // postfix_expression       
    { {       300}, {  48} }, // unary_operator           
    { {       301}, {  49} }, // primary_expression       
    { {       267}, {  50} }, // IDENTIFIER               
    { {       292}, {  51} }, // l_expression             
    { {        45}, {  52} }, // '-'                      
    { {        33}, {  53} }, // '!'                      
    { {       260}, {  54} }, // INT_CONSTANT             
    { {       261}, {  55} }, // FLOAT_CONSTANT           
    { {       268}, {  56} }, // STRING_LITERAL           
    { {        40}, {  57} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_133[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -65} }, 
};

SR__ s_134[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        41}, { 135} }, // ')'  
    { {       273}, {  72} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_135[] =
{
    { { REQ_TOKEN}, {  13} },                        
    { {       287}, { 136} }, // statement           
    { {       123}, {  19} }, // '{'                 
    { {       288}, {  20} }, // selection_statement 
    { {       289}, {  21} }, // iteration_statement 
    { {       290}, {  22} }, // assignment_statement
    { {       262}, {  23} }, // RETURN              
    { {       263}, {  25} }, // IF                  
    { {       265}, {  26} }, // WHILE               
    { {       266}, {  27} }, // FOR                 
    { {        59}, {  28} }, // ';'                 
    { {       292}, {  29} }, // l_expression        
    { {       267}, {  30} }, // IDENTIFIER          
    { {         0}, {   0} },                        
};

SR__ s_136[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 10 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"translation_unit\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 2:
#line 16 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"translation_unit\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 3:
#line 27 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"function_definition\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 4:
#line 39 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"type_specifier\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"VOID\"]\n";
         }
        break;

        case 5:
#line 46 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"type_specifier\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"INT\"]\n";
         }
        break;

        case 6:
#line 53 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"type_specifier\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"FLOAT\"]\n";
         }
        break;

        case 7:
#line 60 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"type_specifier\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"STRING_LITERAL\"]\n";
         }
        break;

        case 8:
#line 71 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"fun_declarator\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"IDENTIFIER\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"(\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\")\"]\n";
         }
        break;

        case 9:
#line 83 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"fun_declarator\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"IDENTIFIER\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"(\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\")\"]\n";
         }
        break;

        case 10:
#line 97 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"parameter_list\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 11:
#line 103 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"parameter_list\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"comma\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 12:
#line 116 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"parameter_declaration\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 13:
#line 127 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"declarator\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"IDENTIFIER\"]\n";
         }
        break;

        case 14:
#line 134 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"declarator\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-3] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"[\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"]\"]\n";
         }
        break;

        case 15:
#line 149 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"constant_expression\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"INT_CONSTANT\"]\n";
         }
        break;

        case 16:
#line 156 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"constant_expression\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"FLOAT_CONSTANT\"]\n";
         }
        break;

        case 17:
#line 166 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"compound_statement\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"{\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"}\"]\n";
         }
        break;

        case 18:
#line 175 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"compound_statement\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"{\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"}\"]\n";
         }
        break;

        case 19:
#line 185 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"compound_statement\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"{\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"}\"]\n";
         }
        break;

        case 20:
#line 200 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"statement_list\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 21:
#line 206 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"statement_list\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 22:
#line 217 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"statement\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"{\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"}\"]\n";
         }
        break;

        case 23:
#line 227 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"statement\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 24:
#line 233 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"statement\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 25:
#line 239 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"statement\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 26:
#line 245 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"statement\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"RETURN\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\";\"]\n";
         }
        break;

        case 27:
#line 259 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"assignment_statement\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\";\"]\n";
         }
        break;

        case 28:
#line 266 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"assignment_statement\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-3] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"=\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\";\"]\n";
         }
        break;

        case 29:
#line 281 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 30:
#line 287 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"OR_OP\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 31:
#line 300 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"logical_and_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 32:
#line 306 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"logical_and_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"AND_OP\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 33:
#line 319 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"equality_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 34:
#line 325 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"equality_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"EQ_OP\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 35:
#line 334 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"equality_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"NE_OP\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 36:
#line 346 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"relational_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 37:
#line 352 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"relational_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"<\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 38:
#line 361 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"relational_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\">\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 39:
#line 370 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"relational_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"LE_OP\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 40:
#line 379 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"relational_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"GE_OP\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 41:
#line 392 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"additive_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 42:
#line 398 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"additive_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"+\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 43:
#line 407 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"additive_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"-\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 44:
#line 420 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"multiplicative_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 45:
#line 426 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"multiplicative_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"*\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 46:
#line 435 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"multiplicative_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"/\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 47:
#line 447 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"unary_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 48:
#line 453 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"unary_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 49:
#line 464 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"postfix_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 50:
#line 470 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"postfix_expression\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"IDENTIFIER\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"(\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\")\"]\n";
         }
        break;

        case 51:
#line 481 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"postfix_expression\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"IDENTIFIER\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"(\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\")\"]\n";
         }
        break;

        case 52:
#line 493 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"postfix_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"INC_OP\"]\n";
         }
        break;

        case 53:
#line 504 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"primary_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 54:
#line 510 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"primary_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"=\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 55:
#line 519 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"primary_expression\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"INT_CONSTANT\"]\n";
         }
        break;

        case 56:
#line 526 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"primary_expression\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"FLOAT_CONSTANT\"]\n";
         }
        break;

        case 57:
#line 533 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"primary_expression\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"STRING_LITERAL\"]\n";
         }
        break;

        case 58:
#line 540 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"primary_expression\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"(\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\")\"]\n";
         }
        break;

        case 59:
#line 553 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"l_expression\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"IDENTIFIER\"]\n";
         }
        break;

        case 60:
#line 560 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"l_expression\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-3] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"[\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"]\"]\n";
         }
        break;

        case 61:
#line 574 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"expression_list\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 62:
#line 580 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"expression_list\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\",\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 63:
#line 592 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"unary_operator\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"-\"]\n";
         }
        break;

        case 64:
#line 599 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"unary_operator\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"!\"]\n";
         }
        break;

        case 65:
#line 609 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"selection_statement\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"IF\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"(\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-4] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\")\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"ELSE\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 66:
#line 628 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"iteration_statement\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"WHILE\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"(\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\")\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 67:
#line 641 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"iteration_statement\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"FOR\"]\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\"(\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-6] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\";\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-4] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\";\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\")\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 68:
#line 663 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"declaration_list\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 69:
#line 669 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"declaration_list\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 70:
#line 679 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"declaration\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << d_vsp__[-1] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\";\"]\n";
         }
        break;

        case 71:
#line 691 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"declarator_list\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

        case 72:
#line 697 "parse.y"
        {
         d_val__ = ++nodecount;
         std::cout << d_val__ << "[label=\"declarator_list\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[-2] << "\n";
         std::cout << d_val__ << " -> " << ++nodecount << "\n";
         std::cout << nodecount << "[label=\",\"]\n";
         std::cout << d_val__ << " -> " << d_vsp__[0] << "\n";
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



